// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704034754_MachineSessionNowHasCreatedAtAndStartedAtAttributes")]
    partial class MachineSessionNowHasCreatedAtAndStartedAtAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Garment", b =>
                {
                    b.Property<int>("GarmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GarmentId"));

                    b.Property<string>("GarmentDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GarmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GarmentId");

                    b.ToTable("Garments");
                });

            modelBuilder.Entity("Domain.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineId"));

                    b.Property<DateOnly>("InstallDate")
                        .HasColumnType("date");

                    b.Property<string>("MachineModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Domain.Models.MachineSession", b =>
                {
                    b.Property<int>("MachineSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GarmentId")
                        .HasColumnType("integer");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MachineSessionId");

                    b.HasIndex("GarmentId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperationId");

                    b.HasIndex("OrderId");

                    b.ToTable("MachineSessions");
                });

            modelBuilder.Entity("Domain.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<double>("BaseTime")
                        .HasColumnType("double precision");

                    b.Property<int>("GarmentId")
                        .HasColumnType("integer");

                    b.Property<string>("OperationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitsPerGarment")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("GarmentId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Domain.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Models.OrderGarment", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("GarmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "GarmentId");

                    b.HasIndex("GarmentId");

                    b.ToTable("OrderGarments");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeIdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MachineEvent", b =>
                {
                    b.Property<int>("MachineEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineEventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int?>("MachineId")
                        .HasColumnType("integer");

                    b.Property<int?>("MachineSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MachineEventId");

                    b.HasIndex("MachineId");

                    b.HasIndex("MachineSessionId");

                    b.ToTable("MachineEvent");

                    b.HasDiscriminator<string>("EventType").HasValue("MachineEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.OperationLog", b =>
                {
                    b.HasBaseType("MachineEvent");

                    b.HasDiscriminator().HasValue("OperationLog");
                });

            modelBuilder.Entity("MachineExceptionLog", b =>
                {
                    b.HasBaseType("MachineEvent");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("MachineExceptionLog");
                });

            modelBuilder.Entity("Domain.Models.MachineSession", b =>
                {
                    b.HasOne("Domain.Models.Garment", "Garment")
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Order", "Order")
                        .WithMany("MachineSessions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garment");

                    b.Navigation("Machine");

                    b.Navigation("Operation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Models.Operation", b =>
                {
                    b.HasOne("Domain.Models.Garment", "Garment")
                        .WithMany("Operations")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garment");
                });

            modelBuilder.Entity("Domain.Models.OrderGarment", b =>
                {
                    b.HasOne("Domain.Models.Garment", "Garment")
                        .WithMany("OrderGarments")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Order", "Order")
                        .WithMany("OrderGarments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MachineEvent", b =>
                {
                    b.HasOne("Domain.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId");

                    b.HasOne("Domain.Models.MachineSession", "MachineSession")
                        .WithMany("Events")
                        .HasForeignKey("MachineSessionId");

                    b.Navigation("Machine");

                    b.Navigation("MachineSession");
                });

            modelBuilder.Entity("Domain.Models.Garment", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("OrderGarments");
                });

            modelBuilder.Entity("Domain.Models.MachineSession", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Domain.Models.Order", b =>
                {
                    b.Navigation("MachineSessions");

                    b.Navigation("OrderGarments");
                });
#pragma warning restore 612, 618
        }
    }
}
